### ISSUE TITLE
Not detecting yaml in v1.1.1?

### ISSUE THREAD

**Issue by ns-cweber** [Depado/bfchroma#6]
The following section seems to not be highlighted as YAML, and I'm not sure why not (ignore the backslashes; I had to "escape" the code fences or it breaks github rendering--GH doesn't support nested code fences afaict):

```
\`\`\`yaml
pipelines:
  default:
    - step:
        services:
          - docker
        caches:
          - docker
        script:
          - docker build -t weberc2/neon:latest .
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          - docker tag weberc2/neon weberc2/neon:$BITBUCKET_COMMIT
          - docker push weberc2/neon:latest
          - docker push weberc2/neon:$BITBUCKET_COMMIT
\`\`\`
```

I assume it's user error, but I'm not really sure how to set about debugging.
